In [1]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.10/dist-packages (from ucimlrepo) (2024.12.14)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [11]:
from ucimlrepo import fetch_ucirepo
#fetch dataset
adult =fetch_ucirepo(id=2)
#data (as pandas dataframes)
X=adult.data.features
y=adult.data.targets

#metadata
print(adult.metadata)
print(adult.variables)

{'uci_id': 2, 'name': 'Adult', 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult', 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv', 'abstract': 'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 48842, 'num_features': 14, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1996, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5XW20', 'creators': ['Barry Becker', 'Ronny Kohavi'], 'intro_paper': None, 'additional_info': {'summary': "Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the following conditions: ((AAGE>16) && (AGI>100) && (AFNLWGT>1)&& (HRSWK>0))\n\nPrediction task is to determine whether a person's income is over $50,000 a year.\n", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Listing of attributes:\r\n\r\n>50K, <=50K.\r\n\r\nage: continuous.\r\nworkclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.\r\nfnlwgt: continuous.\r\neducation: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.\r\neducation-num: continuous.\r\nmarital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.\r\noccupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.\r\nrelationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.\r\nrace: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.\r\nsex: Female, Male.\r\ncapital-gain: continuous.\r\ncapital-loss: continuous.\r\nhours-per-week: continuous.\r\nnative-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.', 'citation': None}}
              name     role  ... units missing_values
0              age  Feature  ...  None             no
1        workclass  Feature  ...  None            yes
2           fnlwgt  Feature  ...  None             no
3        education  Feature  ...  None             no
4    education-num  Feature  ...  None             no
5   marital-status  Feature  ...  None             no
6       occupation  Feature  ...  None            yes
7     relationship  Feature  ...  None             no
8             race  Feature  ...  None             no
9              sex  Feature  ...  None             no
10    capital-gain  Feature  ...  None             no
11    capital-loss  Feature  ...  None             no
12  hours-per-week  Feature  ...  None             no
13  native-country  Feature  ...  None            yes
14          income   Target  ...  None             no

[15 rows x 7 columns]

In [12]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       47879 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      47876 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48568 non-null  object
dtypes: int64(6), object(8)
memory usage: 5.2+ MB

In [13]:
X.isna().sum()

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
dtype: int64

In [14]:
X.head()

   age         workclass  fnlwgt  ... capital-loss  hours-per-week native-country
0   39         State-gov   77516  ...            0              40  United-States
1   50  Self-emp-not-inc   83311  ...            0              13  United-States
2   38           Private  215646  ...            0              40  United-States
3   53           Private  234721  ...            0              40  United-States
4   28           Private  338409  ...            0              40           Cuba

[5 rows x 14 columns]

In [8]:
print(adult.variables)

              name     role  ... units missing_values
0              age  Feature  ...  None             no
1        workclass  Feature  ...  None            yes
2           fnlwgt  Feature  ...  None             no
3        education  Feature  ...  None             no
4    education-num  Feature  ...  None             no
5   marital-status  Feature  ...  None             no
6       occupation  Feature  ...  None            yes
7     relationship  Feature  ...  None             no
8             race  Feature  ...  None             no
9              sex  Feature  ...  None             no
10    capital-gain  Feature  ...  None             no
11    capital-loss  Feature  ...  None             no
12  hours-per-week  Feature  ...  None             no
13  native-country  Feature  ...  None            yes
14          income   Target  ...  None             no

[15 rows x 7 columns]

In [15]:
cat=X['workclass'].unique()
cat

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked',
       nan], dtype=object)

In [16]:
X['occupation'].unique()

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing', 'Machine-op-inspct',
       'Tech-support', '?', 'Protective-serv', 'Armed-Forces',
       'Priv-house-serv', nan], dtype=object)

In [17]:
X['workclass'].mode()

0    Private
Name: workclass, dtype: object

In [18]:
X['occupation'].mode()

0    Prof-specialty
Name: occupation, dtype: object

In [20]:
X['workclass'].fillna(X['workclass'].mode()[0],inplace=True)

<ipython-input-20-c860d2db8f0c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['workclass'].fillna(X['workclass'].mode()[0],inplace=True)

In [21]:
X['occupation'].fillna(X['occupation'].mode()[0],inplace=True)

<ipython-input-21-376b107753a5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X['occupation'].fillna(X['occupation'].mode()[0],inplace=True)
<ipython-input-21-376b107753a5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['occupation'].fillna(X['occupation'].mode()[0],inplace=True)

In [22]:
X.isna().sum()

age                 0
workclass           0
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation          0
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
dtype: int64

In [24]:
X.dropna()

       age         workclass  fnlwgt  ... capital-loss  hours-per-week native-country
0       39         State-gov   77516  ...            0              40  United-States
1       50  Self-emp-not-inc   83311  ...            0              13  United-States
2       38           Private  215646  ...            0              40  United-States
3       53           Private  234721  ...            0              40  United-States
4       28           Private  338409  ...            0              40           Cuba
...    ...               ...     ...  ...          ...             ...            ...
48837   39           Private  215419  ...            0              36  United-States
48838   64           Private  321403  ...            0              40  United-States
48839   38           Private  374983  ...            0              50  United-States
48840   44           Private   83891  ...            0              40  United-States
48841   35      Self-emp-inc  182148  ...            0              60  United-States

[48568 rows x 14 columns]

In [25]:
X.dropna(inplace=True)

<ipython-input-25-32f8c2353909>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.dropna(inplace=True)

In [27]:
X.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
dtype: int64